# Generated by Django 5.0.4 on 2024-04-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_customuser_gender_alcoholintake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bac',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cigarette_toxins',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
