# Generated by Django 5.0.4 on 2024-04-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_customuser_bac_customuser_cigarette_toxins'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='alcohol_toxins',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
